"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=^$_5btvqpjs@s6kvy(^r&b_p4sys@)k=r43$2+mq#5-ck1@07'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']  # Allow mobile app access

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_NAME = 'csrftoken'  # Use default so Django admin/JS pick it up


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # For number formatting (intcomma filter)
    'students_app',
    'ai_question_generator',
    # REST Framework
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS for mobile app
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'students_app.context_processors.current_school',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# settings.py में
# settings.py में
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'school_erp_db',           # ⬅️ Workbench में बनाया गया डेटाबेस नाम
        'USER': 'root',                    # ⬅️ MySQL सुपरयूजर
        'PASSWORD': 'Shubham@1220', 
        'HOST': '127.0.0.1',                 
        'PORT': '3306',                      
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Razorpay Configuration
RAZORPAY_KEY_ID = 'rzp_test_your_key_id'
RAZORPAY_KEY_SECRET = 'your_key_secret'

# Debug print for Razorpay
print(f"Razorpay Key: {RAZORPAY_KEY_ID}")

# Twilio Configuration for SMS and WhatsApp
# Get these from https://www.twilio.com/console
TWILIO_ACCOUNT_SID = ''  # Your Twilio Account SID
TWILIO_AUTH_TOKEN = ''    # Your Twilio Auth Token
TWILIO_PHONE_NUMBER = ''  # Your Twilio phone number (e.g., '+1234567890')
TWILIO_WHATSAPP_NUMBER = 'whatsapp:+14155238886'  # Twilio WhatsApp sandbox number

# Email Configuration
DEFAULT_FROM_EMAIL = 'noreply@schoolerp.com'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Use console for development
# For production, use: 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'students_app.authentication.MultiUserAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/admin-dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Admin URL
ADMIN_URL = 'super-admin/'

# Communication System Encryption
# Generate a key using: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# IMPORTANT: Keep this key secure and never commit it to version control in production
# For production, use environment variables or a secrets management system
# Example: COMMUNICATION_ENCRYPTION_KEY = 'your-generated-key-here'
try:
    # Try to import from environment variable first
    import os
    COMMUNICATION_ENCRYPTION_KEY = os.environ.get('COMMUNICATION_ENCRYPTION_KEY')
    if not COMMUNICATION_ENCRYPTION_KEY:
        # Generate a default key for development (NOT for production!)
        from cryptography.fernet import Fernet
        COMMUNICATION_ENCRYPTION_KEY = Fernet.generate_key().decode()
        print("WARNING: Using auto-generated encryption key. Set COMMUNICATION_ENCRYPTION_KEY in settings or environment for production!")
except ImportError:
    # If cryptography is not installed, set to None (will need to install it)
    COMMUNICATION_ENCRYPTION_KEY = None
    print("WARNING: cryptography library not installed. Install with: pip install cryptography")

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'students_app.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS Configuration for Mobile App
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:19006",  # Expo default
]

# Allow all origins in development (change in production)
CORS_ALLOW_ALL_ORIGINS = True  # Set to False in production

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')