# Generated by Django 5.2.6 on 2025-10-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_image', models.ImageField(help_text='Background image for the ID card.', upload_to='id_card_templates/')),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('width', models.IntegerField(default=338)),
                ('height', models.IntegerField(default=528)),
                ('is_active', models.BooleanField(default=True)),
                ('photo_x', models.IntegerField(default=10)),
                ('photo_y', models.IntegerField(default=10)),
                ('photo_width', models.IntegerField(default=100)),
                ('photo_height', models.IntegerField(default=120)),
                ('name_x', models.IntegerField(default=10)),
                ('name_y', models.IntegerField(default=200)),
                ('name_font_size', models.IntegerField(default=18)),
                ('admission_no_x', models.IntegerField(default=10)),
                ('admission_no_y', models.IntegerField(default=220)),
                ('class_x', models.IntegerField(default=10)),
                ('class_y', models.IntegerField(default=240)),
                ('contact_x', models.IntegerField(default=10)),
                ('contact_y', models.IntegerField(default=260)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('qr_code_x', models.IntegerField(default=200)),
                ('qr_code_y', models.IntegerField(default=20)),
                ('qr_code_size', models.IntegerField(default=50)),
                ('show_blood_group', models.BooleanField(default=True)),
                ('show_dob', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('lost', 'Lost'), ('replaced', 'Replaced')], default='active', max_length=10)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated_id_cards/')),
                ('qr_code_data', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students_app.student')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.idcardtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
