# Generated by Cursor assistant to add Exam, ExamSchedule, and Marks models

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_bookcategory_bus_timeslot_transportroute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('term', models.CharField(choices=[('unit', 'Unit Test'), ('midterm', 'Mid Term'), ('final', 'Final Exam'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.academicyear')),
            ],
            options={'ordering': ['-start_date', 'name']},
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('max_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students_app.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject')),
            ],
            options={'ordering': ['exam_date']},
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.examschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.student')),
            ],
            options={'ordering': ['student__roll_number']},
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('exam', 'subject', 'class_assigned')},
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'exam_schedule')},
        ),
    ]



