# Generated by Cursor assistant to add ClassTest and ClassTestScore

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_exams_and_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('max_marks', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject')),
            ],
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='ClassTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_test_scores', to='students_app.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students_app.classtest')),
            ],
            options={'ordering': ['student__roll_number']},
        ),
        migrations.AlterUniqueTogether(
            name='classtestscore',
            unique_together={('test', 'student')},
        ),
    ]


