# Generated by Django 5.2.6 on 2025-10-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0005_class_tests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='examschedule',
            options={'ordering': ['exam_date'], 'verbose_name': 'Exam Schedule', 'verbose_name_plural': 'Exam Schedules'},
        ),
        migrations.AlterModelOptions(
            name='marks',
            options={'ordering': ['student__roll_number'], 'verbose_name': 'Mark', 'verbose_name_plural': 'Marks'},
        ),
    ]
