# Generated by Cursor assistant to add QuestionPaper

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0005_class_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('questions', models.TextField(help_text='Store as plain text or lightweight markup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject')),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]


