# Generated by Django 5.2.6 on 2025-10-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_alter_exam_options_alter_examschedule_options_and_more'),
        ('students_app', '0006_question_paper'),
    ]

    operations = [
    ]
