# Generated by Django 5.2.6 on 2025-10-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0007_merge_20251006_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Gyanodaya School', max_length=200)),
                ('school_address', models.TextField(default='123 Education Street, Learning City')),
                ('school_phone', models.CharField(default='+91-1234567890', max_length=20)),
                ('school_email', models.EmailField(default='info@gyanodaya.edu', max_length=254)),
                ('school_website', models.URLField(blank=True, null=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('affiliation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('board', models.CharField(default='CBSE', max_length=100)),
                ('receipt_footer_text', models.TextField(default='This is a computer generated receipt and does not require signature.\nFor any queries, please contact the school office.', help_text='Text to display at the bottom of receipts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
