# Generated by Django 5.2.6 on 2025-10-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0008_schoolsettings'),
    ]

    operations = [
    ]
