# Generated by Django 5.2.6 on 2025-10-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0012_activitycategory_canteenitem_certificatetemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('condition_type', models.CharField(help_text='e.g., score_100, complete_5_games', max_length=50)),
                ('condition_value', models.IntegerField(help_text='Value needed to unlock achievement')),
                ('points_reward', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🎮', max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Game Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('game_type', models.CharField(choices=[('quiz', 'Quiz'), ('puzzle', 'Puzzle'), ('memory', 'Memory Game'), ('word', 'Word Game'), ('number', 'Number Game'), ('science', 'Science Experiment'), ('story', 'Story Game')], default='quiz', max_length=20)),
                ('instructions', models.TextField(help_text='How to play the game')),
                ('learning_objectives', models.TextField(help_text='What students will learn')),
                ('time_limit', models.IntegerField(default=300, help_text='Time limit in seconds')),
                ('max_score', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='students_app.class')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='students_app.gamecategory')),
            ],
            options={
                'ordering': ['class_level__numeric_value', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('drag_drop', 'Drag and Drop'), ('matching', 'Matching'), ('sequence', 'Sequence')], default='multiple_choice', max_length=20)),
                ('points', models.IntegerField(default=10)),
                ('time_limit', models.IntegerField(default=30, help_text='Time limit in seconds')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='students_app.educationalgame')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students_app.gamequestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(default=0, help_text='Time taken in seconds')),
                ('is_completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='students_app.educationalgame')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='students_app.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentGameAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='students_app.gameachievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_achievements', to='students_app.student')),
            ],
            options={
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
