# Generated by Django 5.2.6 on 2025-10-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0014_mocktestcategory_mocktest_mocktestquestion_and_more'),
    ]

    operations = [
    ]
