# Generated by Django 5.2.6 on 2025-10-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0015_auto_20251008_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'period_number']},
        ),
        # Skip rename if field doesn't exist - will be handled by migration 0018
        # migrations.RenameField(
        #     model_name='staff',
        #     old_name='salary',
        #     new_name='current_salary',
        # ),
        # These fields may not exist in all database states - handled conditionally
        # migrations.RemoveField(
        #     model_name='staff',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='staff',
        #     name='is_active',
        # ),
        # migrations.RemoveField(
        #     model_name='staff',
        #     name='updated_at',
        # ),
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
        migrations.AddField(
            model_name='staff',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='students_app.class'),
        ),
        migrations.AddField(
            model_name='staff',
            name='assigned_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='students_app.section'),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='education_level',
            field=models.CharField(default='Bachelor Degree', help_text='Specific degree details', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='previous_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='subjects_expertise',
            field=models.ManyToManyField(blank=True, related_name='staff_teachers', to='students_app.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('core', 'Core Subject'), ('language', 'Language'), ('science', 'Science'), ('mathematics', 'Mathematics'), ('social', 'Social Studies'), ('creative', 'Creative Arts'), ('physical', 'Physical Education'), ('technology', 'Technology')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students_app.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_substitute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='substitute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_timetables', to='students_app.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(choices=[('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD'), ('b_ed', 'B.Ed'), ('m_ed', 'M.Ed'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='bachelor', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teacher_subjects', to='students_app.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students_app.section'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students_app.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students_app.staff'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='weekday',
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_name', 'section', 'day', 'period_number')},
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('rtgs', 'RTGS'), ('neft', 'NEFT'), ('online', 'Online Banking')], max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='students_app.staff')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('staff', 'month', 'year')},
            },
        ),
    ]
