# Generated by Django 5.2.6 on 2025-10-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0016_alter_staff_options_alter_subject_options_and_more'),
    ]

    operations = [
    ]
