# Generated by Django 5.2.6 on 2025-10-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0017_auto_20251008_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='salary',
            new_name='current_salary',
        ),
    ]
