# Generated by Django 5.2.6 on 2025-10-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0018_rename_salary_teacher_current_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('single', 'Single Card'), ('multi', 'Multi Card')], default='multi', max_length=10)),
                ('page_size', models.CharField(choices=[('A4', 'A4 (10 cards per page)'), ('12x18', '12x18 (25 cards per page)')], default='A4', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('school_name', models.CharField(default='ABC School', max_length=200)),
                ('school_address', models.TextField(blank=True)),
                ('school_phone', models.CharField(blank=True, max_length=20)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('card_width', models.IntegerField(default=90, help_text='Width in mm')),
                ('card_height', models.IntegerField(default=120, help_text='Height in mm')),
                ('border_color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('admission_no', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('roll_number', models.CharField(blank=True, max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='id_card_photos/')),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_data', to='students_app.idcardgenerator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
