# Generated by Django 5.2.6 on 2025-10-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0019_idcardgenerator_idcarddata'),
    ]

    operations = [
    ]
