# Generated by Django - School Feature Configuration Model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0026_create_fee_enhancement_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeatureConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_enabled', models.BooleanField(blank=True, help_text='None = use global, True/False = override', null=True)),
                ('erp_enabled', models.BooleanField(blank=True, null=True)),
                ('id_card_generator', models.BooleanField(blank=True, null=True)),
                ('fee_payment_online', models.BooleanField(blank=True, null=True)),
                ('attendance_tracking', models.BooleanField(blank=True, null=True)),
                ('marks_entry', models.BooleanField(blank=True, null=True)),
                ('library_management', models.BooleanField(blank=True, null=True)),
                ('transport_management', models.BooleanField(blank=True, null=True)),
                ('hostel_management', models.BooleanField(blank=True, null=True)),
                ('canteen_management', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='students_app.school')),
            ],
            options={
                'verbose_name': 'School Feature Configuration',
                'verbose_name_plural': 'School Feature Configurations',
                'db_table': 'students_app_schoolfeatureconfiguration',
            },
        ),
    ]

