# Generated by Django - Security Settings Model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0027_add_school_feature_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_2fa', models.BooleanField(default=False, help_text='Require 2FA for all admin users')),
                ('password_min_length', models.IntegerField(default=8, help_text='Minimum password length')),
                ('password_complexity', models.BooleanField(default=True, help_text='Require uppercase, lowercase, numbers, and symbols')),
                ('session_timeout', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('ip_whitelist_enabled', models.BooleanField(default=False, help_text='Restrict access to specific IP addresses')),
                ('audit_logging', models.BooleanField(default=True, help_text='Log all user actions and system changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
                'db_table': 'students_app_securitysettings',
            },
        ),
    ]



