# Generated by Django 5.2.6 on 2025-12-02 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0033_extend_feature_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_encrypted', models.BooleanField(default=False)),
                ('submission_type', models.CharField(choices=[('digital', 'Digital Only'), ('physical', 'Physical Only'), ('both', 'Both Digital and Physical')], default='digital', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('instructions', models.TextField(blank=True)),
                ('instructions_encrypted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_file', models.FileField(blank=True, null=True, upload_to='assignments/submissions/digital/')),
                ('digital_text', models.TextField(blank=True)),
                ('digital_text_encrypted', models.BooleanField(default=False)),
                ('digital_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('physical_submitted', models.BooleanField(default=False)),
                ('physical_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('physical_remarks', models.CharField(blank=True, max_length=500)),
                ('physical_remarks_encrypted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late Submission'), ('missing', 'Missing')], default='submitted', max_length=20)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('feedback_encrypted', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationEventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('parent_meeting', 'Parent Meeting'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('target_audience', models.CharField(default='all', help_text='all, class, section, or specific', max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='events/')),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_encrypted', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/')),
                ('instructions', models.TextField(blank=True)),
                ('instructions_encrypted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationHomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='homework/submissions/')),
                ('submission_text', models.TextField(blank=True)),
                ('submission_text_encrypted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('late', 'Late'), ('not_submitted', 'Not Submitted')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('remarks_encrypted', models.BooleanField(default=False)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('period_number', models.IntegerField()),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_assigned', 'section', 'day', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('enquiries', models.IntegerField(default=0)),
                ('contacted', models.IntegerField(default=0)),
                ('qualified', models.IntegerField(default=0)),
                ('applications', models.IntegerField(default=0)),
                ('enrolled', models.IntegerField(default=0)),
                ('enquiry_to_contact_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('contact_to_qualify_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('qualify_to_apply_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('apply_to_enroll_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_enrollment_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('teacher_parent', 'Teacher to Parent'), ('parent_teacher', 'Parent to Teacher'), ('teacher_student', 'Teacher to Student'), ('student_teacher', 'Student to Teacher')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_encrypted', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='Device name/model', max_length=200)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=50)),
                ('os_version', models.CharField(blank=True, help_text='OS version', max_length=50)),
                ('app_version', models.CharField(blank=True, help_text='App version installed', max_length=50)),
                ('first_installed', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Device is currently active')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional device info')),
            ],
            options={
                'verbose_name': 'Mobile Device',
                'verbose_name_plural': 'Mobile Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='monthlysalary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date', 'student__first_name'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='healthcheckup',
            options={'ordering': ['-checkup_date', 'student__first_name'], 'verbose_name': 'Health Checkup', 'verbose_name_plural': 'Health Checkups'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-year', '-month', 'employee__user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='salarycomponent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['weekday', 'time_slot']},
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='other_deductions',
            new_name='deductions',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='students_ap_status_5f635e_idx',
            old_name='students_ap_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='students_ap_assigne_ff053d_idx',
            old_name='students_ap_assigned_status_idx',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='generated_file',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='is_downloaded',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='certificate_number_x',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='certificate_number_y',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='date_x',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='date_y',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='signature_x',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='signature_y',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='blood_pressure_diastolic',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='blood_pressure_systolic',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='clinic_hospital',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='dental_health',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='doctor_qualification',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='hearing',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='pulse_rate',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='vision_left',
        ),
        migrations.RemoveField(
            model_name='healthcheckup',
            name='vision_right',
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='fixed_amount',
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('section', 'academic_year', 'weekday', 'time_slot')},
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificate_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificate_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='status',
            field=models.CharField(default='issued', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='dental_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='doctor_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='hearing_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='vision_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='is_librarian',
            field=models.BooleanField(default=False, help_text='Is this staff member a librarian?'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(default='2024-25', on_delete=django.db.models.deletion.CASCADE, to='students_app.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students_app.timeslot'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students_app.certificatetemplate'),
        ),
        migrations.AlterField(
            model_name='healthcheckup',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckup',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='students_app.staff'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Basic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='students_app.section'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students_app.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.teacher'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.teacher'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students_app.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.teacher'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.student'),
        ),
        migrations.AddField(
            model_name='communicationeventschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationeventschedule',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.class'),
        ),
        migrations.AddField(
            model_name='communicationeventschedule',
            name='target_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.section'),
        ),
        migrations.AddField(
            model_name='communicationhomework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject'),
        ),
        migrations.AddField(
            model_name='communicationhomework',
            name='target_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.class'),
        ),
        migrations.AddField(
            model_name='communicationhomework',
            name='target_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.section'),
        ),
        migrations.AddField(
            model_name='communicationhomework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.teacher'),
        ),
        migrations.AddField(
            model_name='communicationhomeworksubmission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students_app.communicationhomework'),
        ),
        migrations.AddField(
            model_name='communicationhomeworksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.student'),
        ),
        migrations.AddField(
            model_name='communicationtimetable',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.class'),
        ),
        migrations.AddField(
            model_name='communicationtimetable',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.section'),
        ),
        migrations.AddField(
            model_name='communicationtimetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.subject'),
        ),
        migrations.AddField(
            model_name='communicationtimetable',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentfunnel',
            unique_together={('date',)},
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='related_student',
            field=models.ForeignKey(blank=True, help_text='Student this message is about', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MonthlySalary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='generated_payslip',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='overtime',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='provident_fund',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='is_substitute',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_number',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='substitute_reason',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='substitute_teacher',
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher', 'target_class'], name='students_ap_teacher_9fe2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date', 'status'], name='students_ap_due_dat_9ef7a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='communicationhomeworksubmission',
            unique_together={('homework', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='communicationtimetable',
            unique_together={('class_assigned', 'section', 'day', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient'], name='students_ap_sender__62e090_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'created_at'], name='students_ap_is_read_3ad431_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['device_id'], name='students_ap_device__dc7036_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['user', 'is_active'], name='students_ap_user_id_da17af_idx'),
        ),
    ]
