# Generated by Django 5.2.6 on 2025-12-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0034_assignment_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='apaar_id',
            field=models.CharField(blank=True, help_text='12-digit Automated Permanent Academic Account Registry ID', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certificates/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
