# Generated by Django 5.2.6 on 2025-12-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0035_student_apaar_id_alter_student_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='students_app.school'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('school', 'isbn')},
        ),
    ]
