# Generated by Django 5.2.6 on 2025-12-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0036_add_school_to_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='students_app.school'),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='idcardtemplate',
            unique_together={('school', 'name')},
        ),
    ]
