# Generated by Django 5.2.6 on 2025-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0038_add_school_to_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='optional_subject_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional fee for optional subjects (Class 9)', max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='stream',
            field=models.CharField(blank=True, choices=[('general', 'General (No Stream)'), ('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('math_science', 'Math-Science'), ('biology_science', 'Biology-Science')], default='general', help_text='Select stream for classes 9-12 (Science, Commerce, Arts, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Select specific subjects for this fee structure (optional)', related_name='fee_structures', to='students_app.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_assigned', 'academic_year', 'stream')},
        ),
    ]
