# Generated by Django 5.2.6 on 2025-12-23 17:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0039_alter_feestructure_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(help_text='e.g., Technician, Sales Executive, Support Staff', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('parents', 'Parents Only'), ('teachers', 'Teachers Only'), ('staff', 'Staff Only')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('erp_setup', 'ERP Setup & Configuration'), ('id_card', 'ID Card Generation'), ('camera_installation', 'Camera Installation'), ('system_installation', 'System/Hardware Installation'), ('printing_material', 'Printing Material Supply'), ('training', 'Staff Training'), ('maintenance', 'System Maintenance'), ('troubleshooting', 'Troubleshooting & Support'), ('data_migration', 'Data Migration'), ('customization', 'Software Customization'), ('other', 'Other Work')], max_length=50)),
                ('title', models.CharField(help_text='Brief title of the work', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of work done')),
                ('location', models.CharField(help_text='Work location/address', max_length=200)),
                ('work_date', models.DateField(help_text='Date when work was done')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('hours_spent', models.DecimalField(blank=True, decimal_places=2, help_text='Number of hours spent on this work', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_entries', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='students_app.school')),
                ('team_members', models.ManyToManyField(blank=True, related_name='work_entries', to='students_app.teammember')),
            ],
            options={
                'verbose_name': 'Work Entry',
                'verbose_name_plural': 'Work Entries',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('travel', 'Travel & Transportation'), ('material', 'Material/Hardware Purchase'), ('printing', 'Printing & Stationery'), ('food', 'Food & Accommodation'), ('software', 'Software/License'), ('installation', 'Installation Charges'), ('labor', 'Labor Charges'), ('misc', 'Miscellaneous')], max_length=50)),
                ('description', models.CharField(help_text='What was this expense for?', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_by', models.CharField(choices=[('company', 'Company'), ('team_member', 'Team Member')], default='company', max_length=20)),
                ('expense_date', models.DateField(help_text='Date of expense')),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt/bill number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_member', models.ForeignKey(blank=True, help_text='If paid by team member, select who paid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.teammember')),
                ('work_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='students_app.workentry')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
