# Generated by Django 6.0 on 2025-12-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0040_teammember_event_status_event_target_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
