# Generated by Django 6.0 on 2025-12-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0041_notice_published_at_notice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Non-Teaching Staff', 'verbose_name_plural': 'Non-Teaching Staff'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Teaching Staff', 'verbose_name_plural': 'Teaching Staff'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    # Add school_id to staff if it doesn't exist
                    """
                    SET @dbname = DATABASE();
                    SET @tablename = 'students_app_staff';
                    SET @columnname = 'school_id';
                    SET @preparedStatement = (SELECT IF(
                      (
                        SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                        WHERE
                          (table_name = @tablename)
                          AND (table_schema = @dbname)
                          AND (column_name = @columnname)
                      ) > 0,
                      'SELECT 1',
                      CONCAT('ALTER TABLE ', @tablename, ' ADD COLUMN school_id INT NULL, ADD FOREIGN KEY (school_id) REFERENCES students_app_school(id)')
                    ));
                    PREPARE alterIfNotExists FROM @preparedStatement;
                    EXECUTE alterIfNotExists;
                    DEALLOCATE PREPARE alterIfNotExists;
                    """,
                    reverse_sql=migrations.RunSQL.noop
                ),
                migrations.RunSQL(
                    # Add school_id to teacher if it doesn't exist
                    """
                    SET @dbname = DATABASE();
                    SET @tablename = 'students_app_teacher';
                    SET @columnname = 'school_id';
                    SET @preparedStatement = (SELECT IF(
                      (
                        SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                        WHERE
                          (table_name = @tablename)
                          AND (table_schema = @dbname)
                          AND (column_name = @columnname)
                      ) > 0,
                      'SELECT 1',
                      CONCAT('ALTER TABLE ', @tablename, ' ADD COLUMN school_id INT NULL, ADD FOREIGN KEY (school_id) REFERENCES students_app_school(id)')
                    ));
                    PREPARE alterIfNotExists FROM @preparedStatement;
                    EXECUTE alterIfNotExists;
                    DEALLOCATE PREPARE alterIfNotExists;
                    """,
                    reverse_sql=migrations.RunSQL.noop
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='staff',
                    name='school',
                    field=models.ForeignKey(blank=True, help_text='School this staff member belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='students_app.school'),
                ),
                migrations.AddField(
                    model_name='teacher',
                    name='school',
                    field=models.ForeignKey(blank=True, help_text='School this teacher belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='students_app.school'),
                ),
            ]
        ),
        migrations.RunSQL(
            # Add unique constraint if it doesn't exist
            """
            SET @dbname = DATABASE();
            SET @tablename = 'students_app_staff';
            SET @constraintname = 'students_app_staff_school_id_employee_id_uniq';
            SET @preparedStatement = (SELECT IF(
              (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                WHERE
                  (table_name = @tablename)
                  AND (table_schema = @dbname)
                  AND (constraint_name = @constraintname)
              ) > 0,
              'SELECT 1',
              CONCAT('ALTER TABLE ', @tablename, ' ADD UNIQUE KEY ', @constraintname, ' (school_id, employee_id)')
            ));
            PREPARE alterIfNotExists FROM @preparedStatement;
            EXECUTE alterIfNotExists;
            DEALLOCATE PREPARE alterIfNotExists;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.ForeignKey(help_text='Non-teaching staff category', on_delete=django.db.models.deletion.CASCADE, to='students_app.staffcategory'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_librarian',
            field=models.BooleanField(default=False, help_text='Is this staff member a librarian? (Non-teaching role)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.RunSQL(
            # Add unique constraint if it doesn't exist
            """
            SET @dbname = DATABASE();
            SET @tablename = 'students_app_teacher';
            SET @constraintname = 'students_app_teacher_school_id_employee_id_uniq';
            SET @preparedStatement = (SELECT IF(
              (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                WHERE
                  (table_name = @tablename)
                  AND (table_schema = @dbname)
                  AND (constraint_name = @constraintname)
              ) > 0,
              'SELECT 1',
              CONCAT('ALTER TABLE ', @tablename, ' ADD UNIQUE KEY ', @constraintname, ' (school_id, employee_id)')
            ));
            PREPARE alterIfNotExists FROM @preparedStatement;
            EXECUTE alterIfNotExists;
            DEALLOCATE PREPARE alterIfNotExists;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='staff',
                    unique_together={('school', 'employee_id')},
                ),
                migrations.AlterUniqueTogether(
                    name='teacher',
                    unique_together={('school', 'employee_id')},
                ),
            ]
        ),
        migrations.RunSQL(
            # Remove fields if they exist
            """
            SET @dbname = DATABASE();
            SET @tablename = 'students_app_staff';
            
            -- Remove assigned_class_id if exists
            SET @columnname = 'assigned_class_id';
            SET @preparedStatement = (SELECT IF(
              (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                WHERE
                  (table_name = @tablename)
                  AND (table_schema = @dbname)
                  AND (column_name = @columnname)
              ) > 0,
              CONCAT('ALTER TABLE ', @tablename, ' DROP COLUMN ', @columnname),
              'SELECT 1'
            ));
            PREPARE alterIfExists FROM @preparedStatement;
            EXECUTE alterIfExists;
            DEALLOCATE PREPARE alterIfExists;
            
            -- Remove assigned_section_id if exists
            SET @columnname = 'assigned_section_id';
            SET @preparedStatement = (SELECT IF(
              (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                WHERE
                  (table_name = @tablename)
                  AND (table_schema = @dbname)
                  AND (column_name = @columnname)
              ) > 0,
              CONCAT('ALTER TABLE ', @tablename, ' DROP COLUMN ', @columnname),
              'SELECT 1'
            ));
            PREPARE alterIfExists FROM @preparedStatement;
            EXECUTE alterIfExists;
            DEALLOCATE PREPARE alterIfExists;
            
            -- Remove is_class_teacher if exists
            SET @columnname = 'is_class_teacher';
            SET @preparedStatement = (SELECT IF(
              (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                WHERE
                  (table_name = @tablename)
                  AND (table_schema = @dbname)
                  AND (column_name = @columnname)
              ) > 0,
              CONCAT('ALTER TABLE ', @tablename, ' DROP COLUMN ', @columnname),
              'SELECT 1'
            ));
            PREPARE alterIfExists FROM @preparedStatement;
            EXECUTE alterIfExists;
            DEALLOCATE PREPARE alterIfExists;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='staff',
                    name='assigned_class',
                ),
                migrations.RemoveField(
                    model_name='staff',
                    name='assigned_section',
                ),
                migrations.RemoveField(
                    model_name='staff',
                    name='is_class_teacher',
                ),
            ]
        ),
    ]
