# Generated by Django 5.2.6 on 2025-12-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0043_add_teacher_staff_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='face_match_confidence',
            field=models.FloatField(blank=True, help_text='Face match confidence score', null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='face_match_result',
            field=models.BooleanField(blank=True, help_text='Face verification result (True if match, False if no match)', null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='ocr_extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data extracted from ID card using OCR', null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='verification_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('ocr', 'OCR'), ('face', 'Face Verification'), ('both', 'OCR + Face')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='verification_photo',
            field=models.ImageField(blank=True, help_text='Photo used for verification', null=True, upload_to='attendance_verification/staff/'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='face_match_confidence',
            field=models.FloatField(blank=True, help_text='Face match confidence score', null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='face_match_result',
            field=models.BooleanField(blank=True, help_text='Face verification result (True if match, False if no match)', null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='ocr_extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data extracted from ID card using OCR', null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='verification_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('ocr', 'OCR'), ('face', 'Face Verification'), ('both', 'OCR + Face')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='verification_photo',
            field=models.ImageField(blank=True, help_text='Photo used for verification', null=True, upload_to='attendance_verification/teachers/'),
        ),
    ]
