# Generated by Django 5.2.6 on 2025-12-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0044_add_verification_fields_to_attendance'),
    ]

    operations = [
        # Note: Removed RemoveField for staff.subjects_expertise as table doesn't exist
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_address',
            field=models.BooleanField(default=False, help_text='Show address'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_admission_no',
            field=models.BooleanField(default=True, help_text='Show admission number'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_class',
            field=models.BooleanField(default=True, help_text='Show class'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_father_name',
            field=models.BooleanField(default=False, help_text='Show father name'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_guardian_name',
            field=models.BooleanField(default=False, help_text='Show guardian name'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_mobile',
            field=models.BooleanField(default=False, help_text='Show mobile number'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_mother_name',
            field=models.BooleanField(default=False, help_text='Show mother name'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_name',
            field=models.BooleanField(default=True, help_text='Show student name'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_photo',
            field=models.BooleanField(default=True, help_text='Show student photo'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='show_section',
            field=models.BooleanField(default=True, help_text='Show section'),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='show_blood_group',
            field=models.BooleanField(default=False, help_text='Show blood group'),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='show_dob',
            field=models.BooleanField(default=False, help_text='Show date of birth'),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='show_qr_code',
            field=models.BooleanField(default=True, help_text='Show QR code'),
        ),
    ]
