# Generated by Django 5.2.6 on 2025-12-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0045_add_id_card_display_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('lost', 'Lost'), ('replaced', 'Replaced')], default='active', max_length=10)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated_id_cards/staff/')),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code data for attendance punching', null=True)),
                ('qr_code_hash', models.CharField(blank=True, help_text='Hash for QR code verification', max_length=64, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students_app.staff')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students_app.teacher')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.idcardtemplate')),
            ],
            options={
                'verbose_name': 'Staff ID Card',
                'verbose_name_plural': 'Staff ID Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
