# Generated by Django 5.2.6 on 2025-12-30 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0046_add_staff_id_card_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Skip RemoveField for subjects_expertise as it may not exist
        # migrations.RemoveField(
        #     model_name='staff',
        #     name='subjects_expertise',
        # ),
        migrations.AddField(
            model_name='schoolsettings',
            name='twilio_account_sid',
            field=models.CharField(blank=True, help_text='Twilio Account SID from https://www.twilio.com/console', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='twilio_auth_token',
            field=models.CharField(blank=True, help_text='Twilio Auth Token (keep secure)', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='twilio_enabled',
            field=models.BooleanField(default=False, help_text='Enable WhatsApp/SMS messaging via Twilio'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='twilio_phone_number',
            field=models.CharField(blank=True, help_text='Twilio phone number (e.g., +1234567890)', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='twilio_whatsapp_number',
            field=models.CharField(blank=True, default='whatsapp:+14155238886', help_text='Twilio WhatsApp number (sandbox or approved)', max_length=50),
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('requested_due_date', models.DateField(help_text='Expected return date')),
                ('purpose', models.TextField(blank=True, help_text='Purpose for borrowing the book')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('issued', 'Issued'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('actual_due_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_book_requests', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='students_app.book')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_requests', to='students_app.teacher')),
            ],
            options={
                'verbose_name': 'Book Request',
                'verbose_name_plural': 'Book Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
