# Generated by Django 5.2.6 on 2025-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0048_create_bookrequest_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subjects_expertise',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='structured_questions',
            field=models.JSONField(blank=True, default=list, help_text='Structured questions with types and templates'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.TextField(blank=True, help_text='Store as plain text or lightweight markup'),
        ),
    ]
