# Generated by Django 5.2.6 on 2025-12-31 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0049_remove_staff_subjects_expertise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting the change')),
                ('preferred_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], help_text='Preferred day if changing day', null=True)),
                ('preferred_room', models.CharField(blank=True, help_text='Preferred room if changing room', max_length=50)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information or suggestions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's response or notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.academicyear')),
                ('current_timetable_entry', models.ForeignKey(blank=True, help_text='The timetable entry that needs to be changed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='students_app.timetable')),
                ('preferred_section', models.ForeignKey(blank=True, help_text='Preferred section if changing class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.section')),
                ('preferred_subject', models.ForeignKey(blank=True, help_text='Preferred subject if changing subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.subject')),
                ('preferred_time_slot', models.ForeignKey(blank=True, help_text='Preferred time slot if changing time', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.timeslot')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_timetable_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_change_requests', to='students_app.teacher')),
            ],
            options={
                'verbose_name': 'Timetable Change Request',
                'verbose_name_plural': 'Timetable Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
