# Generated by Django 5.2.6 on 2026-01-01 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0050_add_timetable_change_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Phone number used for verification', max_length=15)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verified Device',
                'verbose_name_plural': 'Verified Devices',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['device_id', 'user'], name='students_ap_device__45659d_idx'), models.Index(fields=['user', 'is_active'], name='students_ap_user_id_2b3544_idx')],
                'unique_together': {('device_id', 'user')},
            },
        ),
    ]
