# Generated by Django 5.2.6 on 2026-01-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0051_add_verified_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbilling',
            name='billing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('per_student', 'Per Student')], default='per_student', help_text='Fixed amount or per student', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolbilling',
            name='rate_per_student',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per student (e.g., ₹5, ₹10)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='schoolbilling',
            name='student_count',
            field=models.IntegerField(blank=True, help_text='Number of active students at billing time', null=True),
        ),
    ]
