# Generated by Django 5.2.6 on 2026-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0052_add_per_student_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Teacher', max_length=50),
        ),
    ]
