# Generated by Django 5.2.6 on 2026-02-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0053_add_designation_to_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='designation',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
