# Generated by Django 5.2.6 on 2026-02-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0054_student_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_card',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar Card Number', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='samagra_id',
            field=models.CharField(blank=True, help_text='9-digit Samagra ID', max_length=9, null=True),
        ),
    ]
