# Generated by Django 5.2.6 on 2026-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0055_student_aadhaar_card_student_samagra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='address_x',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='address_y',
            field=models.IntegerField(default=340),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='blood_group_x',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='blood_group_y',
            field=models.IntegerField(default=380),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='dob_x',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='dob_y',
            field=models.IntegerField(default=360),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='father_x',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='father_y',
            field=models.IntegerField(default=280),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='guardian_x',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='guardian_y',
            field=models.IntegerField(default=320),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='mother_x',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='mother_y',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='section_x',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='section_y',
            field=models.IntegerField(default=240),
        ),
    ]
