# Generated by Django 5.2.6 on 2026-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0056_idcardtemplate_address_x_idcardtemplate_address_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcardtemplate',
            name='address_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='address_y',
            field=models.IntegerField(blank=True, default=340, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='admission_no_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='admission_no_y',
            field=models.IntegerField(blank=True, default=220, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='blood_group_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='blood_group_y',
            field=models.IntegerField(blank=True, default=380, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='class_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='class_y',
            field=models.IntegerField(blank=True, default=240, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='contact_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='contact_y',
            field=models.IntegerField(blank=True, default=260, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='dob_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='dob_y',
            field=models.IntegerField(blank=True, default=360, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='father_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='father_y',
            field=models.IntegerField(blank=True, default=280, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='guardian_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='guardian_y',
            field=models.IntegerField(blank=True, default=320, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='mother_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='mother_y',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='name_font_size',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='name_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='name_y',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='photo_height',
            field=models.IntegerField(blank=True, default=120, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='photo_width',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='photo_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='photo_y',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='qr_code_size',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='qr_code_x',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='qr_code_y',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='section_x',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='section_y',
            field=models.IntegerField(blank=True, default=240, null=True),
        ),
    ]
